import React from 'react';

export default function Footer() {
  return (
    <footer className="px-4 sm:px-[6vw] pt-12 sm:pt-16 pb-8 sm:pb-10 border-t border-white/10 relative z-10 font-sans text-white bg-[#050507]">
      <div className="footer-top flex flex-col sm:flex-row justify-between gap-8 sm:gap-10 mb-8 sm:mb-12">
        {/* Logo */}
        <div className="space-y-2">
          <a href="#home" className="flex items-center gap-3">
            <img
              src="/images/logo_cropped.png"
              alt="Third AI Commercials"
              className="h-9 sm:h-10 w-auto object-contain"
            />
            <span className="font-display font-semibold text-base sm:text-lg tracking-wider text-white">
              THIRD AI<span className="text-gray-400 font-light">.COMMERCIALS</span>
            </span>
          </a>
          <p className="text-xs font-mono text-gray-400 pl-[48px] sm:pl-[52px]">Haripad, Alappuzha, Kerala</p>
        </div>

        {/* Footer Columns */}
        <div className="footer-links grid grid-cols-3 sm:flex sm:gap-[60px] gap-6">
          <div className="footer-col space-y-2 sm:space-y-3">
            <h4 className="font-display text-[10px] sm:text-xs tracking-widest text-gray-400 uppercase font-semibold">Studio</h4>
            {['Home','About','Vault','Services','Process','Reviews','FAQ','Contact'].map(link => (
              <a key={link} href={`#${link.toLowerCase()}`} className="block text-xs sm:text-sm text-gray-400 hover:text-white transition">{link}</a>
            ))}
          </div>

          <div className="footer-col space-y-2 sm:space-y-3">
            <h4 className="font-display text-[10px] sm:text-xs tracking-widest text-gray-400 uppercase font-semibold">Connect</h4>
            <a href="https://www.instagram.com/kaelix.ai/reels/" target="_blank" rel="noopener noreferrer" className="block text-xs sm:text-sm text-gray-400 hover:text-white transition">Instagram</a>
            <a href="tel:+919539101061" className="block text-xs sm:text-sm text-gray-400 hover:text-white transition font-mono">+91 95391 01061</a>
          </div>

          <div className="footer-col space-y-2 sm:space-y-3">
            <h4 className="font-display text-[10px] sm:text-xs tracking-widest text-gray-400 uppercase font-semibold">Contact</h4>
            <a href="mailto:Thirdaicommercials@gmail.com" className="block text-xs sm:text-sm text-gray-400 hover:text-white transition font-mono break-all">
              Thirdaicommercials@gmail.com
            </a>
          </div>
        </div>
      </div>

      <div className="footer-bottom flex flex-col sm:flex-row justify-between text-gray-500 text-[11px] sm:text-xs gap-1 sm:gap-3 pt-5 sm:pt-6 border-t border-white/5 font-mono">
        <span>© {new Date().getFullYear()} THIRD AI COMMERCIALS LLP — All rights reserved.</span>
        <span>Generated by imagination.</span>
      </div>
    </footer>
  );
}
